/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnimationParams { 'type' : string, 'speed' : bigint }
export interface ColorScheme {
  'accent' : string,
  'secondary' : string,
  'primary' : string,
}
export interface GlowEffect { 'color' : string, 'intensity' : bigint }
export interface PandaCard {
  'id' : bigint,
  'glowEffect' : GlowEffect,
  'rarity' : string,
  'colorScheme' : ColorScheme,
  'animationParams' : AnimationParams,
}
export interface _SERVICE {
  'getAllCards' : ActorMethod<[], Array<PandaCard>>,
  'getBaseGlowEffectIntensity' : ActorMethod<[], bigint>,
  'getCardById' : ActorMethod<[bigint], PandaCard>,
  'getCardCount' : ActorMethod<[], bigint>,
  'getCardsByRarity' : ActorMethod<[string], Array<PandaCard>>,
  'getRandomCard' : ActorMethod<[], PandaCard>,
  'initialize' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];