/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GlowEffect = IDL.Record({
  'color' : IDL.Text,
  'intensity' : IDL.Nat,
});
export const ColorScheme = IDL.Record({
  'accent' : IDL.Text,
  'secondary' : IDL.Text,
  'primary' : IDL.Text,
});
export const AnimationParams = IDL.Record({
  'type' : IDL.Text,
  'speed' : IDL.Nat,
});
export const PandaCard = IDL.Record({
  'id' : IDL.Nat,
  'glowEffect' : GlowEffect,
  'rarity' : IDL.Text,
  'colorScheme' : ColorScheme,
  'animationParams' : AnimationParams,
});

export const idlService = IDL.Service({
  'getAllCards' : IDL.Func([], [IDL.Vec(PandaCard)], ['query']),
  'getBaseGlowEffectIntensity' : IDL.Func([], [IDL.Nat], []),
  'getCardById' : IDL.Func([IDL.Nat], [PandaCard], ['query']),
  'getCardCount' : IDL.Func([], [IDL.Nat], []),
  'getCardsByRarity' : IDL.Func([IDL.Text], [IDL.Vec(PandaCard)], ['query']),
  'getRandomCard' : IDL.Func([], [PandaCard], []),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GlowEffect = IDL.Record({ 'color' : IDL.Text, 'intensity' : IDL.Nat });
  const ColorScheme = IDL.Record({
    'accent' : IDL.Text,
    'secondary' : IDL.Text,
    'primary' : IDL.Text,
  });
  const AnimationParams = IDL.Record({ 'type' : IDL.Text, 'speed' : IDL.Nat });
  const PandaCard = IDL.Record({
    'id' : IDL.Nat,
    'glowEffect' : GlowEffect,
    'rarity' : IDL.Text,
    'colorScheme' : ColorScheme,
    'animationParams' : AnimationParams,
  });
  
  return IDL.Service({
    'getAllCards' : IDL.Func([], [IDL.Vec(PandaCard)], ['query']),
    'getBaseGlowEffectIntensity' : IDL.Func([], [IDL.Nat], []),
    'getCardById' : IDL.Func([IDL.Nat], [PandaCard], ['query']),
    'getCardCount' : IDL.Func([], [IDL.Nat], []),
    'getCardsByRarity' : IDL.Func([IDL.Text], [IDL.Vec(PandaCard)], ['query']),
    'getRandomCard' : IDL.Func([], [PandaCard], []),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };